services:
  back:
    image: openjdk:22-jdk
    container_name: voronoi-back
    env_file:
      - .env
    build: src/backend
    ports:
      - $BACK_PORT:$BACK_PORT
  front:
    image: node:lts-alpine
    container_name: voronoi-front
    env_file:
      - .env
    build: src/frontend
    ports:
      - $FRONT_PORT:$FRONT_PORT
