services:
  back:
    image: openjdk:22-jdk
    container_name: voronoi-back
    build: src/backend
    ports:
      - "8080:8080"
  front:
    image: node:lts-alpine
    container_name: voronoi-front
    build: src/frontend
    ports:
      - "3000:3000"
